title: Daniel B Cooper, MPH

logo: me_profile_pic.png # Use a relative path to logo image 

description:  

show_downloads: true 

theme: jekyll-theme-minimal 

plugins:
  - jekyll-seo-tag # Add SEO plugin

email: dcoop.me+cv@gmail.com # Allow visitors to contact you
