title: Daniel B. Cooper

logo: me_profile_pic_round.png # Use a relative path to logo image 

description:  

show_downloads: true 

remote_theme: pages-themes/minimal@v0.2.0
plugins:
- jekyll-remote-theme # add this line to the plugins list if you already have one

email: dcoop.me+cv@gmail.com # Allow visitors to contact you
